- name: 1.1 Ensure a separate partition for containers has been created (Scored)\
  debug: msg="This is a manual configuration"
  tags:
   - not_scored
   - section1.2

- name: 1.2 Ensure the container host has been Hardened (Not Scored)
  debug: msg="Not covered by this role"
  tags:
   - not_scored
   - section1.2

- name: 1.3 Ensure Docker is up to date (Not Scored) | RHEL
  yum:
    name: docker-ce
    state: latest
  tags:
   - not_scored
   - section1.3
  when: ansible_distribution|lower == 'redhat'

- name: 1.3 Ensure Docker is up to date (Not Scored) | Debian like
  apt:
    name: docker-ce
    state: latest
  tags:
   - not_scored
   - section1.3
  when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'

- name: 1.4 Ensure only trusted users are allowed to control Docker daemon (Scored)
  user:
    name: "{{ item }}"
    group: docker 
  with_items: "{{ tursted_users }}"
  tags:
   - scored
   - section1.4

- name: 1.5 Ensure auditd installed | redhat
  yum:
    name: auditd
    state: latest
  tags:
   - not_scored
   - section1.3
  when: 
  - ansible_distribution|lower == 'redhat'
  - ansible_distribution_major_version|lower < 8

- name: 1.5 Ensure auditd installed | redhat
  dnf:
    name: auditd
    state: latest
  tags:
   - not_scored
   - section1.3
  when: 
  - ansible_distribution|lower == 'redhat'
  - ansible_distribution_major_version|lower >= 8

- name: 1.5 Ensure auditd installed | debian like
  apt:
    name: auditd
    state: latest
  tags:
   - not_scored
   - section1.3
  when: ansible_distribution|lower == 'debian' or ansible_distribution|lower == 'ubuntu'

- name: 1.1.3 Ensure auditing is configured for the docker daemon (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules
    line: "-w /usr/bin/dockerd -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.1.3

- name: 1.1.4 Ensure auditing is configured for Docker files and directories - /run/containerd
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules
    line: "-a exit,always -F path=/run/containerd -F perm=war -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.1.4

- name: 1.5 Ensure auditing is configured for the docker daemon (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.5

- name: 1.6 Ensure auditing is configured for Docker files and directories - /var/lib/docker (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /var/lib/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.6


- name: 1.7 Ensure auditing is configured for Docker files and directories - /etc/docker (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.7

- name: 1.8 Ensure auditing is configured for Docker files and directories - docker.service (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/lib/systemd/system/docker.service -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.8

- name: 1.9 Ensure auditing is configured for Docker files and directories - docker.socket (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/lib/systemd/system/docker.socket -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.9

- name: 1.10 Ensure auditing is configured for Docker files and directories - /etc/default/docker (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/default/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.10

- name: 1.11 Ensure auditing is configured for Docker files and directories - /etc/docker/daemon.json (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/docker/daemon.json -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.11

- name: 1.12 Ensure auditing is configured for Docker files and directories - /usr/bin/docker-containerd (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/docker-containerd -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.12

- name: 1.1.12 Ensure auditing is configured for Docker files and directories - /etc/containerd/config.toml
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/containerd/config.toml -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.1.12


- name: 1.13 Ensure auditing is configured for Docker files and directories - /usr/bin/docker-runc (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/docker-runc -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.13

- name: 1.13 Ensure auditing is configured for Docker files and directories - /usr/bin/docker-runc (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/docker-runc -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.13

- name: 1.1.14 Ensure auditing is configured for Docker files and directories - /usr/bin/containerd
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/containerd -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
  - scored
  - section1.14
  
- name: 1.1.15 Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/containerd-shim -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
    - scored
    - section1.15
  
- name: 1.1.16 Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim-runc-v1
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/containerd-shim-runc-v1 -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.16

- name: 1.1.17 Ensure auditing is configured for Docker files and directories - /usr/bin/containerd-shim-runc-v2
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/containerd-shim-runc-v2 -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.17

- name: 1.1.18 Ensure auditing is configured for Docker files and directories - /usr/bin/runc
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/runc -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.18